#ifndef MACRO_H_SPEEDWAY_TREASURE_LUXURY_BRAVERY_FORTUNE_HERBAL_DYNAMITE
#define MACRO_H_SPEEDWAY_TREASURE_LUXURY_BRAVERY_FORTUNE_HERBAL_DYNAMITE

#ifndef bzero
#define bzero(Destination,Length) memset((Destination),0,(Length))
#endif

#ifndef PASS
#define PASS do{}while(0)
#endif

#endif //MACRO_H_SPEEDWAY_TREASURE_LUXURY_BRAVERY_FORTUNE_HERBAL_DYNAMITE
